### ISSUE TITLE
IndexError in save_topology method

### ISSUE THREAD

**Issue by ahmedkh91** [fernandodebrando/p4-int#2]
when I run using : (sudo p4run) I am getting this error message:

Traceback (most recent call last):
  File "/usr/local/bin/p4run", line 33, in <module>
    sys.exit(load_entry_point('p4utils', 'console_scripts', 'p4run')())
  File "/home/p4/p4-tools/p4-utils/p4utils/p4run.py", line 739, in main
    verbosity=args.verbosity)
  File "/home/p4/p4-tools/p4-utils/p4utils/p4run.py", line 359, in __init__
    self.startNetwork()
  File "/home/p4/p4-tools/p4-utils/p4utils/mininetlib/network_API.py", line 1120, in startNetwork
    self.save_topology()
  File "/home/p4/p4-tools/p4-utils/p4utils/mininetlib/network_API.py", line 204, in save_topology
    subnet1 = _prefixLenMatchRegex.findall(intf1.ifconfig())[0]
IndexError: list index out of range
![image](https://user-images.githubusercontent.com/56312416/163081496-19c2ed6e-98d1-4446-9178-7fbdeefc90aa.png)

**Comment by Fu-LianPeng** [comment]
have you solved this problem? I also meet this problem,if you have solution ,can you please teach me
